### ISSUE TITLE
PDF not supported in various browsers

### ISSUE THREAD

**Issue by fmcmanus** [pipwerks/PDFObject#113]
Hi, I tested my app, build in ASP .NET MVC 5 C# using PDFObject to view PDF inside a page, but it fails in this conditions:

Windows 10: FireFox 50 (in another Windows 10 device with Firefox, same version, works fine ¿¿¿???)
Android 4.4.4: Firefox 49
Android 6.0.1: Chrome 52.0.2840.85
ios 10.1.1: Safari

Is something I'm doing wrong? Does it requires a plug-in? Does it works in Mobile devices?

Thanks

**Comment by pipwerks** [comment]
All PDFObject does is embed the PDF in the HTML, if the browser supports the PDF MIME type. The browser handles the actual PDF rendering. Older browsers will require a PDF rendering plugin, such as Adobe Reader for IE9.

Some mobile operating systems do not support inline PDFs (PDFs embedded in an HTML page). For example, Safari in iOS will render a PDF when you navigate to the PDF's URL, but not when the PDF is embedded in an HTML page. (If I remember correctly, iOS would successfully display the first page of a PDF as an image, but you would not be able to scroll or navigate to subsequent pages within the PDF.)

To fully check browser support, try embedding the same PDF into the same ASP page using pure HTML markup, without JavaScript. If the PDF displays when using pure markup but not when using JS, it will indicate the problem lies with PDFObject. 

If you want to ensure all browsers support your PDF, you can use PDF.js to control the rendering yourself. Here is an example https://pdfobject.com/examples/pdfjs-forced.html
