### ISSUE TITLE
Safari iOS 10.1 update for embedded PDF support

### ISSUE THREAD

**Issue by c-simpson** [pipwerks/PDFObject#116]
https://pdfobject.com/static.html  says " As of iOS 9, none of these examples work properly in Safari for iOS."

Under 10.1, the `<object>, <embed>`,  and `<object><iframe></object> ` methods show the first page only and do not allow scrolling or paging.  `<iframe>` renders at about 400% so only a little of Page 1 is visible.

**Comment by pipwerks** [comment]
Hi Chris

I don't see an action item in this submission, I'm not sure what you're trying to report.

FWIW, I may not have been clear on the homepage, but the expected behavior is that Safari for iOS will NOT embed PDFs properly. When I say PDFObject has been tested in Safari for iOS, I mean that it will properly report PDFs cannot be displayed inline, precisely because of the behavior you outline above.

**Comment by pipwerks** [comment]
Also note PDF.js works on Safari for iOS; if iOS is a concern for you, I suggest using PDF.js to force the PDF to render inline.

**Comment by yiakwy** [comment]
PDF.js is memory consuming. We should not use that.

**Comment by pipwerks** [comment]
@yiakwy Safari for iOS does not support inline PDFs. The options are: render the PDF yourself using something like PDF.js (which is unrelated to PDFObject) or don't try to embed PDFs inline.
