### ISSUE TITLE
HTML5 embed tag

### ISSUE THREAD

**Issue by raojx** [pipwerks/PDFObject#13]
Any plan to support HTML5 embed tag? The object tag doesn't always work on mobile browsers.

**Comment by pipwerks** [comment]
Almost three years have passed since this question was posed, it's definitely still relative. FWIW I'm looking into using `<embed>` now that it's officially supported in the HTML5 spec (and HTML5 is now official). For pure markup (no JS) I still recommend `<object>` since it provides a fallback mechanism.
