### ISSUE TITLE
PDF as data URI

### ISSUE THREAD

**Issue by guillaumegarcia13** [pipwerks/PDFObject#131]
Because of authorization issues (I cannot set the Authorization Header...), I would like to use a data URI such as this:

`new PDFObject.embed('data:application/pdf;base64,JVBERi0xLjcKCjEgMCBvYmogICUgZW50cnkgcG9pbnQKPDwKICAvVHlwZSAvQ2F0YWxvZwogIC9QYWdlcyAyIDAgUgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKICAvVHlwZSAvUGFnZXMKICAvTWVkaWFCb3ggWyAwIDAgMjAwIDIwMCBdCiAgL0NvdW50IDEKICAvS2lkcyBbIDMgMCBSIF0KPj4KZW5kb2JqCgozIDAgb2JqCjw8CiAgL1R5cGUgL1BhZ2UKICAvUGFyZW50IDIgMCBSCiAgL1Jlc291cmNlcyA8PAogICAgL0ZvbnQgPDwKICAgICAgL0YxIDQgMCBSIAogICAgPj4KICA+PgogIC9Db250ZW50cyA1IDAgUgo+PgplbmRvYmoKCjQgMCBvYmoKPDwKICAvVHlwZSAvRm9udAogIC9TdWJ0eXBlIC9UeXBlMQogIC9CYXNlRm9udCAvVGltZXMtUm9tYW4KPj4KZW5kb2JqCgo1IDAgb2JqICAlIHBhZ2UgY29udGVudAo8PAogIC9MZW5ndGggNDQKPj4Kc3RyZWFtCkJUCjcwIDUwIFRECi9GMSAxMiBUZgooSGVsbG8sIHdvcmxkISkgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDEwIDAwMDAwIG4gCjAwMDAwMDAwNzkgMDAwMDAgbiAKMDAwMDAwMDE3MyAwMDAwMCBuIAowMDAwMDAwMzAxIDAwMDAwIG4gCjAwMDAwMDAzODAgMDAwMDAgbiAKdHJhaWxlcgo8PAogIC9TaXplIDYKICAvUm9vdCAxIDAgUgo+PgpzdGFydHhyZWYKNDkyCiUlRU9G', '#pdf', options);`

In Chrome I get a net::ERR_INVALID_URL error.
Besides, I'm not sure I'll be able to load large PDF this way.

**Comment by pipwerks** [comment]
I have not tried data URIs, but the bottom line is: If you can get it working via plain markup, it should work via PDFObject. PDFObject's primary task is dynamically writing an `<embed>` to the page. Try testing to see if you can get the data URI working with static markup. Here is a generator to help you create the static markup: https://pdfobject.com/generator/

Since this is a usage question and not an issue with PDFObject, I will mark this thread as closed. If your static markup works and PDFObject does not, please let me know and I will reopen this issue.

**Comment by guillaumegarcia13** [comment]
Finally, for anyone interested, I used a blob like this:

```
$http({method      : 'GET',
       url         : endpoint,
       responseType: 'arraybuffer'})
   .then(function(response) {
       var file       = new Blob([response.data], {type: 'application/pdf'});
       var fileURL    = URL.createObjectURL(file);
       //$sce.trustAsResourceUrl(fileURL);
       var success    = new PDFObject.embed(fileURL, '#pdf', options);            
   });
```

**Comment by pipwerks** [comment]
Thank you for sharing, good luck
