### ISSUE TITLE
Using Blob's ObjectUrl on IE (Internet Explorer)

### ISSUE THREAD

**Issue by rfreitas** [pipwerks/PDFObject#136]
ObjectUrls (created from Blobs) don't work on IE.
So PDF Object will inject the `<embed>` element (because IE 11+ supports PDF rendering), but an error message will be displayed instead by the browser, not the PDFObject link fallback.

I wonder whether this library should own that and display the fallback. Also to display a downloadable link for an Blob ObjectUrl on IE, I believe one has to use IE method `msSaveOrOpenBlob`.

yay IE!

**Comment by pipwerks** [comment]
Hi rfreitas 

Interesting use case, but also an edge case -- if you're advanced enough to be using blobs instead of PDF files, I imagine you'd be able to add conditional logic to your web app that avoids attempting to embed the blob when the end user has IE11.

Most PDFObject users are pointing to static PDF files, not blobs or base64 strings. 

Also, you mention "IE 11+ supports PDF rendering", but if I recall correctly IE11 requires a 3rd-party plugin for PDF support.

**Comment by andaleebroomy** [comment]
I am also facing this. I prefer to use the blob URL instead of an http url because I can show the progress/loader in the UI when I download the PDF by myself. If I give it to PDFObject, I have no way to know when the download completed.
