### ISSUE TITLE
[question] Why cannot I see the PDFs? 

### ISSUE THREAD

**Issue by kittaakos** [pipwerks/PDFObject#160]
Hi there,

I tried to use `PDFObject` to embed PDFs in our single page application, and it did not work as I have expected. I went through the examples and checked a few tutorials here and there still it does not seem to work, so I thought it worth a question here.

I put together a partially [working example in JSFiddle](http://jsfiddle.net/kittaakos/kfy5dsbe/) then I got stuck.
 - It does not show anything in Safari (`11.0.3 (13604.5.6)`).
 - It does not show anything in Chrome (`65.0.3325.181`) **if** I disable Chrome's [`PDF Viewer extension`](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm). If the extension is **enabled**, it works perfectly.
 - It does not work on FF (`60.0b5 `) either but at least it shows the `This browser does not support inline PDFs. Please download the PDF to view it: Download PDF` message.

If I get the source from JSFiddle and copy into a local `index.html` file and I open it up in any of the three browsers, it works.

I have also tried the followings:
```html
<embed src="https://ptgmedia.pearsoncmg.com/images/9780672335952/samplepages/0672335956.pdf" width="600" height="500" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html">
```

```html
<object data="https://ptgmedia.pearsoncmg.com/images/9780672335952/samplepages/0672335956.pdf"></object>
```

These work only **if** I turn the PDF Viewer browser extension on in Chrome. Otherwise, nothing is visible. Also, the `https://docs.google.com/viewer?url=your_url_to_pdf&embedded=true` way in an `iframe` is not an option for me; sometimes I have to server PDFs from `localhost`.

Could you please advise what could be the problem? Am I facing a JSFiddle issue here or did I mess up something in my local environment? Thank you!

**Comment by kittaakos** [comment]
It seems to be a problem with JSFiddle, but I would leave this issue open and wait for some response from an expert.

**Comment by pipwerks** [comment]
If you disable the native PDF support, the browser will still behave as if PDFs are supported, making PDFObject embed the PDF. Nothing we can do about it, but that use case (disabling native PDF support) is very unlikely.

Your static markup tests prove the point -- if the `<embed>` fails when hard-coded, it must be a browser issue.

PDFObject has a known issue with Firefox, check the issues list and the fix in the latest beta (dev branch).

As for JSFiddle, it's blocking your PDF from loading. See the error in the console:
`Failed to load 'https://ptgmedia.pearsoncmg.com/images/9780672335952/samplepages/0672335956.pdf' as a plugin, because the frame into which the plugin is loading is sandboxed`

**Comment by kittaakos** [comment]
Thanks for the explanation! I am closing this; it works as expected in the application.

> As for JSFiddle, it's blocking your PDF from loading

I have overlooked that.
