### ISSUE TITLE
not suport chrome android anymore

### ISSUE THREAD

**Issue by r0b78** [pipwerks/PDFObject#183]
In the last month don't show the button to down load the pdf on android

**Comment by pipwerks** [comment]
PDFObject has never provided a button for downloading a file on Android.

**Comment by leonelgalan** [comment]
I'm on Chrome 75.0.3770.89 and I see this:

![Screenshot_20190613-111257](https://user-images.githubusercontent.com/727774/59444906-af92f780-8dcc-11e9-8ddf-ab47bf7fad91.png)

My co-worker on chrome 74.0.3729.157 sees it without the "Open" button. Clicking on where the button should be downloads the PDF.

![Screenshot_20190613-111257 (1)](https://user-images.githubusercontent.com/727774/59445003-d6e9c480-8dcc-11e9-9edc-72ed0069bce4.png)

@pipwerks, from the docs and your response I guess it's not PDFObject adding this button it's the browser doing/not doing it instead. That said, `PDFObject.supportsPDFs` appears to work correctly, we both see the _IN case you were wondering, your browser does not support embedded PDFs. Sad Pandas._ message. Instead of relying on this button to show or not, we can create our own button and show it instead of the object tag using `PDFObject.supportsPDFs` to branch.

**Comment by pipwerks** [comment]
Thanks for the info. Correct, PDFObject is not adding this button. The default is a link, which Chrome on Android must be converting to a button. You can replace the default message (and the link/button) by specifying your own `fallbackLink`. 

Also note: the default text is `<p>This browser does not support inline PDFs. Please download the PDF to view it: <a href='[url]'>Download PDF</a></p>`.

**Comment by pipwerks** [comment]
Hello. 

I have confirmed Android browsers were adding the button because they were not capable of displaying the PDF and did not know how to handle it.

PDFObject 2.2.0 fixes this issue -- Android browsers now correctly display your fallback content instead of the download button.  See commits in dev branch and test cases at https://pdfobject.com/dev/

2.2.0 will be released as soon as I can finish testing, hopefully this week. If you have some time, please kick the tires and let me know if you run into any issues. Thanks
