### ISSUE TITLE
PDFObject fails to load which has not defined file extension (.pdf)

### ISSUE THREAD

**Issue by muhammadumairaslam** [pipwerks/PDFObject#201]
Hi,

PDFObject fails to load PDF file that has no file extension (**.pdf**) like
[https://test.com/files/4ed29509e9b96cb568b95fff3d7a3b6b](https://test.com/files/4ed29509e9b96cb568b95fff3d7a3b6b) 

That issue i m facing now with only new browser version. Chrome result as look like this
![image](https://user-images.githubusercontent.com/15632135/72083513-c4fcdf80-3323-11ea-9f5a-4e65e5769c46.png)

IE is working fine.
![image](https://user-images.githubusercontent.com/15632135/72083880-4f454380-3324-11ea-9462-e5faff648bbc.png)

**Comment by johnhunter** [comment]
Hi, your issue is probably not with PDFObject itself. The webserver should serve the file with an `application/pdf` mime type. If the file has no `.pdf` extension then the webserver may not be able to tell what kind of file it is so serves it with the default (probably `text/plain`) so the browser will display the file source as you indicate. IE uses a plugin to display pdfs so the plugin might not look at the mime type and just attempt to render content as pdf.

**Comment by pipwerks** [comment]
PDFObject simply inserts an `<embed>` element in the HTML for you. A quick test is to hand-code an `<embed>` with the URL in a plain HTML page. If it works there, it should work in PDFObject.

**Comment by pipwerks** [comment]
FYI I have tested multiple embeds without .PDF extension and they work fine. I assume this was an issue on your server. Please let me know if you're still having issues.
