### ISSUE TITLE
Get PDF with credentials.

### ISSUE THREAD

**Issue by creinelt** [pipwerks/PDFObject#229]
Is there a way to enable credentials for the request?
We want to get the file from an API Endpoint which needs authentication via API token.

**Comment by pipwerks** [comment]
No, sorry. PDFObject simply embeds PDFs into the page. You'd need to write a custom script to serve the PDF from your API,  then invoke PDFObject once the PDF has served. Plus I imagine you wouldn't want to send API credentials in the clear, so you'd want to handle that via POST/HTTPS (PDFObject uses querystrings for passing params). Definitely outside the scope of PDFObject.

**Comment by creinelt** [comment]
I didn't mean to send it via query params, I was thinking about the same approach you suggested to me, but since I can only provide an Url I was thinking that this is not possible. So there is a way to fetch the document and Athens serve the content to PDFObject?

**Comment by pipwerks** [comment]
PDFObject is a client-side solution using HTML. Your issue is a server-side issue.

If the PDF is served as base64, you could fetch via xmlhttprequest then take the returned value (the base64, as a very long string) and embed it via PDFObject https://pdfobject.com/examples/base64.html. But it's very uncommon for PDFs to be served as base64. 

If the PDF is being served as a binary file (application/pdf), which is the typical scenario, your HTML page is expecting the PDF to be ready to go at whatever URL is supplied. No authentication layer. (Remember, all PDFObject does is write a snippet of HTML to your page.) If the authentication can be resolved via a simple querystring, you can probably use it in plain HTML, which means it would also work in PDFObject.

However, if you can't use a simple querystring to get past the authentication layer, and can't serve the PDF as base64, you'd need to implement a server-side solution such as a proxy server, maybe something like this: https://spin.atomicobject.com/2015/10/03/remote-pfs-node-js-express/. The idea being that the server does the heavy lifting of fetching the PDF from the authenticated server then makes it available without authentication via a different URL. This is well outside the scope of PDFObject and requires a custom solution.

Good luck
