### ISSUE TITLE
PDF shows blank after display none.

### ISSUE THREAD

**Issue by dualmacops** [pipwerks/PDFObject#257]
Steps to reproduce:
1.Go to https://pdfobject.com/ 
2.add display: none; to example1
3.remove it.
![image](https://user-images.githubusercontent.com/9700375/131490400-72aaf886-e74c-4513-ba79-ee4cfdd321be.png)

Tested on Chrome, Opera and Edge

**Comment by pipwerks** [comment]
Browsers often unload hidden embed elements to release memory. This behavior will vary from browser to browser and is beyond the control (or scope) of PDFObject.

Things you can try:
* Try using absolute positioning to move the PDF offscreen instead of using display:none
* Try forcing iframe instead of using the default `<embed>`. There's a chance some browsers will keep iframe content loaded when hidden.
