### ISSUE TITLE
Base64 document can't be downloaded in Safari (iOS)

### ISSUE THREAD

**Issue by architechpro** [pipwerks/PDFObject#270]
When viewing the demo page with PDF encoded as a base64 string (https://pdfobject.com/examples/base64.html) on Safari (iOS), there is a text:

> This browser does not support inline PDFs. Please download the PDF to view it: **Download PDF**

However, when you click **Download PDF**, you'll get following error in console:

```
Not allowed to navigate top frame to data URL 'data:application/pdf;base64,JVBERi0xLjMKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwgL0xlbmd0aCA1IDAgUiAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeAGdWsuS20YSvOMr+siJ8IzZDT6PXtmK8MbaIYfHu4cNHzAkNGoHCFIEMJ+737KZ1VUNUKRkjfYR4oCNRnVWVtYD/Oh+cx/dHP9d+eDW2+DOtfuPa933bzrvdp3zrtt9+v17N39YzeU/Lk6/LHAzvyznfruab9KtEQ/wsuqe//AZu4P7x6MrV+kq/l0H5+cr93hw37/1D3Pni8f3bvZ7dTg1tXv349s79/iX++kRxs656Wc29Bt9zEY2LEPaMDzMC++44eOH2Dn8r3JdtK3d/5r6wb0dWvc+/f9hfNiN5xQwHEgRsXsiBsNXZXpOScP5nP+62b+O5zvn125WH+7c/da7mcO/5dLN4qkbeG29LuTaYutm+2Mj60Na5kt...A1MjA2IDAwMDAwIG4gCjAwMDAwMDc0NzIgMDAwMDAgbiAKMDAwMDAwNzQ5MyAwMDAwMCBuIAowMDAwMDA3NzU1IDAwMDAwIG4gCjAwMDAwMDgxNDYgMDAwMDAgbiAKMDAwMDAxMzE0NiAwMDAwMCBuIAowMDAwMDEzMTY3IDAwMDAwIG4gCjAwMDAwMTM0MjQgMDAwMDAgbiAKMDAwMDAxMzg3NyAwMDAwMCBuIAowMDAwMDE3MDE2IDAwMDAwIG4gCjAwMDAwMTcwMzcgMDAwMDAgbiAKMDAwMDAxNzMwMiAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDI2IC9Sb290IDEzIDAgUiAvSW5mbyAxIDAgUiAvSUQgWyA8NGU5NDk1MTVhYWYxMzI0OThmNjUwZTdiZGU2Y2RjMmY+Cjw0ZTk0OTUxNWFhZjEzMjQ5OGY2NTBlN2JkZTZjZGMyZj4gXSA+PgpzdGFydHhyZWYKMTgxMzIKJSVFT0YK'.
```

The document itself will not be downloaded.

**Comment by theodore-s-beers** [comment]
That's odd. I opened that page in iOS Safari and couldn't get the PDF to download by any means. When I tried in iOS Brave (which is also WebKit-based), I could view the PDF by long-pressing the link and selecting to open it in a new tab. I'm not sure what the problem is with vanilla iOS Safari. Also, if you use macOS Safari and spoof an iOS user agent, the "open in a new tab" option works fine. It's only on an actual iOS device that this becomes more difficult.

Anyway, I can't see how this issue would be caused by PDFObject (though I could be missing something). What PDFObject does in offering a fallback link to download a PDF is very straightforward.

If you need a workaround for iOS Safari, I would suggest converting the base64 string representation of the PDF to an ArrayBuffer, making a blob from that, and putting the blob URL in the `fallbackLink` option for PDFObject. That's just what I've done in this recreation of the demo page:

https://www.theobeers.com/test-base64-pdf/
