### ISSUE TITLE
I am getting "This browser does not support inline PDFs." on Chrome

### ISSUE THREAD

**Issue by Jejugo** [pipwerks/PDFObject#305]
Not sure exactly why but whenever trying to render a PDF we're getting this error "This browser does not support inline PDFs." on Chrome. It was working before and It's working for other browsers though. Any thoughts?

BTW I'm on Mac

**Comment by theodore-s-beers** [comment]
What do you see if you load this page?

<https://pdf-support.pages.dev/>

**Comment by Jejugo** [comment]
![image](https://github.com/user-attachments/assets/7d527676-50cd-4e80-a956-ab9a37f8f3ce)

is this `navigator.pdfViewerEnabled: false` something we need to manually enable on chrome?

**Comment by Jejugo** [comment]
> What do you see if you load this page?
> 
> https://pdf-support.pages.dev/

@theodore-s-beers 
![image](https://github.com/user-attachments/assets/7d527676-50cd-4e80-a956-ab9a37f8f3ce)

is this `navigator.pdfViewerEnabled: false` something we need to manually enable on chrome?

**Comment by theodore-s-beers** [comment]
You shouldn't need to manually enable it; more likely it was manually disabled at some point, and that's why you're seeing the embed failure. In Chrome on macOS, enter Settings, Privacy and security, Site settings, Additional content settings, PDF documents, Open PDFs in Chrome. At least, I _think_ that's what sets this flag.

**Comment by pipwerks** [comment]
Thanks @theodore-s-beers 

@Jejugo I've seen this happen with others as well. Browsers (esp on a fresh install) typically ask if you want to display the PDF in the browser or download it, then will save that preference. It's very possible at some point you were prompted to choose, and didn't realize it would affect future PDF interactions.

FWIW the logic of `navigator.pdfViewerEnabled` is spelled out here: https://pdfobject.com/api/#pdfobject-supportspdfs

I'm on a Mac and just verified it works fine in Chrome.

**Comment by mjau-mjau** [comment]
Same here. From mobile devices (both Android and iPhone), I am getting `This browser does not support inline PDF's ... `. Isn't the point of PDFObject to be able to render PDF's inline on devices that otherwise don't support it? 🤔

![IMG_A3760E7CEF6E-1](https://github.com/user-attachments/assets/abf2758e-5c72-422a-b802-86a1b81d2ec5)

**Comment by pipwerks** [comment]
https://pdfobject.com/guide/why-pdfobject.html#not-a-pdf-rendering-engine

**Comment by mjau-mjau** [comment]
> https://pdfobject.com/guide/why-pdfobject.html#not-a-pdf-rendering-engine

Thanks. I did delete the post a few minutes after I posted 😄 I think I will use some of your detection logic code to decide if PDF can be embedded inline. Thank you sir!
