### ISSUE TITLE
Rendering clientside generated pdf **no url attr**?

### ISSUE THREAD

**Issue by BransonGitomeh** [pipwerks/PDFObject#55]
[pdfmake](https://github.com/bpampuch/pdfmake) and [jspdf](https://github.com/MrRio/jsPDF)

is there a way to render a clientside generated file using the liblaries named above?

on the documentation i can only find

```
var success = new PDFObject({ url: "sample.pdf" }).embed();
```

and yet the **url** attr is unnavailable since the pdf is not comming from the server

any clue how i can use this?...thanks in advance :smiley_cat:

**Comment by pipwerks** [comment]
Hi Branson

Unfortunately, I have not tried the libraries you mentioned.

As-is, PDFObject needs the file URL because it writes an `<object>` to the page, and the HTML `<object>` element requires a `data` attribute. If you don't have a URL for the PDF, you will need to handle the PDF via some other mechanism.

I suggest pinging the authors of those libraries to see how they embed their client-rendered PDFs with an HTML page. They must have some kind of example somewhere, their libraries look really well constructed.

Good luck!
