### ISSUE TITLE
Bootstrap Modal Not Visible in Internet Explorer

### ISSUE THREAD

**Issue by atbyrd** [pipwerks/PDFObject#76]
I'm having a problem when trying to use bootstrap 3 modal in conjunction with PDFObject. I can see the screen get dark but cannot see the actual modal. The active pdf, I have multiple open at once in bootstrap tabs, stay bright and in focus. If I refresh the page I can temporarily see the modal as the page begins to reload.

**Comment by pipwerks** [comment]
Unfortunately, Bootstrap is beyond the scope of PDFObject and not something I'm very familiar with (I use different frameworks). I imagine it's a CSS issue, I suggest checking to see if Bootstrap does anything funky to the modal's child elements, like a display:none or changing z-index.

**Comment by atbyrd** [comment]
I was able to get it working by using the PDF.js. Seem to not be just a bootstrap issues as I tried other javascript libraries and got the same issue.

**Comment by pipwerks** [comment]
Thanks for sharing your PDF.js resolution. 

Might be an Adobe Reader issue, assuming you're using Reader to provide PDF support in IE. Since Reader is a plugin, it renders the PDF outside the flow of the DOM, which can cause issues with layers (z-index). [A similar issue happened with Flash Player, too](http://learnswfobject.com/advanced-topics/placing-html-elements-over-a-flash-movie/index.html), but Adobe Reader does not provide a `wmode` param to like Flash Player does. I'll see if I can replicate the issue and find a workaround, but I won't have time to work on it for a while.
