### ISSUE TITLE
PDF object not getting loaded in android chrome browser

### ISSUE THREAD

**Issue by nisha-kajale** [pipwerks/PDFObject#77]
Hi,

I am trying to load pdf from a different domain in android but it is giving me error saying "This browser does not support inline pdf. Please download pdf to view it."

But when i access https://pdfobject.com/examples/pdfjs-forced.html from my android tablet i am able to view the pdf.

Can you please explain how should i code so that i can force chrome browser to view my pdf which is located at different domain as it is done in https://pdfobject.com/examples/pdfjs-forced.html.

I also tried by loading a pdf file from same domain to check if cross domain is an issue. But still it did not work for me.

Thanks,
Nisha

**Comment by pipwerks** [comment]
The error message is simply telling you your Android browser doesn't support inline PDFs. It's not a PDFObject error. Safari for iOS doesn't natively support PDFs either. 

The PDF.js example works because it bypasses native PDF support and instead uses JavaScript to render the PDF. PDF.js is a separate project, for more information on how to use it, please see their website.

**Comment by nisha-kajale** [comment]
Hi,
Thanks for your reply. I will contact the PDF.js website support for my query.

Regards,
Nisha
